baseURL = 'https://barnz.dev/'
languageCode = 'en-gb'
title = 'My New Hugo Site'
theme = 'bdev'

[module]
  [[module.mounts]]
    source = "assets"
    target = "assets"
  [[module.mounts]]
    source = "node_modules/feather-icons/dist/icons"
    target = "assets/icons"
