baseURL = "https://barnz.dev/"
title = "barnz.dev"
theme = "bdev"
copyright = "barnz.dev"
defaultContentLanguage = 'en'
disableHugoGeneratorInject = true

[languages]
    [languages.en]
        languageName = "English"

    [languages.nl]
        languageName = "Dutch"

    [languages.fr]
        languageName = "French"

[author]
  name = "Barnz"
  email = "hi@barnz.dev"

[params]
  description = "Hello, I am Barnz, a web developer from the UK."

[taxonomies]
  tag = "tags"

[markup]
  [markup.highlight]
    anchorLineNos = false
    codeFences = true
    guessSyntax = true
    hl_Lines = '0 0'
    lineAnchors = ''
    lineNoStart = 1
    lineNos = true
    lineNumbersInTable = true
    noClasses = true
    noHl = false
    style = 'dracula'
    tabWidth = 2

[module]
  [[module.mounts]]
    source = "assets"
    target = "assets"
  [[module.mounts]]
    source = "node_modules/feather-icons/dist/icons"
    target = "assets/icons"
